# Data analysis of "74% of Food Trucks Don’t Display Prices"

## Cleaning Data Imported from Google Maps

In [66]:
import pandas as pd
df = pd.read_csv('/Users/kunihiro-iwasaki/Desktop/Lede/Project/project1/foodtruck_data.csv')
df.head()

,タイトル,メモ,URL,タグ,コメント
0,NaN,NaN,NaN,NaN,NaN
1,指定した地点,48、表示あり。コーヒー、ジュースなど。コールドブリューは$6。一部商品のみ表示,"https://www.google.com/maps/search/40.7644,-73...",NaN,NaN
2,指定した地点,51、表示なし。ジュース、アイス,"https://www.google.com/maps/search/40.7648035,...",NaN,NaN
3,指定した地点,85、表示あり。ホットドッグ、アイス、ドリンク,"https://www.google.com/maps/search/40.7667045,...",NaN,NaN
4,指定した地点,45、表示あり。チキンオーバーライス、ホットドッグなど,"https://www.google.com/maps/search/40.7649919,...",NaN,NaN

In [67]:
df2 = df.drop(columns=['タイトル', 'タグ', 'コメント'])
df2

,メモ,URL
0,NaN,NaN
1,48、表示あり。コーヒー、ジュースなど。コールドブリューは$6。一部商品のみ表示,"https://www.google.com/maps/search/40.7644,-73..."
2,51、表示なし。ジュース、アイス,"https://www.google.com/maps/search/40.7648035,..."
3,85、表示あり。ホットドッグ、アイス、ドリンク,"https://www.google.com/maps/search/40.7667045,..."
4,45、表示あり。チキンオーバーライス、ホットドッグなど,"https://www.google.com/maps/search/40.7649919,..."
...,...,...
81,14、表示なし。ハンバーガー、ホットドッグ、ドリンク,"https://www.google.com/maps/search/40.7760205,..."
82,13、表示なし。ドリンク、スムージー,"https://www.google.com/maps/search/40.776344,-..."
83,12、表示なし。チキンオーバーライス、ケバブ、ドリンクなど,"https://www.google.com/maps/search/40.7795244,..."
84,11、表示なし。ホットドッグ、ハンバーガーなど,"https://www.google.com/maps/search/40.7807488,..."
85,10。表示なし。チキンオーバーライス、ハンバーガー、ホットドッグなど。家族が購入,"https://www.google.com/maps/search/40.7808164,..."

In [68]:
df2['メモ'] = df2['メモ'].str.replace({'、':',', '。':','})
df2

,メモ,URL
0,NaN,NaN
1,"48,表示あり,コーヒー,ジュースなど,コールドブリューは$6,一部商品のみ表示","https://www.google.com/maps/search/40.7644,-73..."
2,"51,表示なし,ジュース,アイス","https://www.google.com/maps/search/40.7648035,..."
3,"85,表示あり,ホットドッグ,アイス,ドリンク","https://www.google.com/maps/search/40.7667045,..."
4,"45,表示あり,チキンオーバーライス,ホットドッグなど","https://www.google.com/maps/search/40.7649919,..."
...,...,...
81,"14,表示なし,ハンバーガー,ホットドッグ,ドリンク","https://www.google.com/maps/search/40.7760205,..."
82,"13,表示なし,ドリンク,スムージー","https://www.google.com/maps/search/40.776344,-..."
83,"12,表示なし,チキンオーバーライス,ケバブ,ドリンクなど","https://www.google.com/maps/search/40.7795244,..."
84,"11,表示なし,ホットドッグ,ハンバーガーなど","https://www.google.com/maps/search/40.7807488,..."
85,"10,表示なし,チキンオーバーライス,ハンバーガー,ホットドッグなど,家族が購入","https://www.google.com/maps/search/40.7808164,..."

## Extract necessary information, such as whether prices are displayed or hidden, and latitude and longitude

In [69]:
df2[['No','price_display','item1','item2','item3','item4','item5']] = df2['メモ'].str.split(',', expand=True)
df2[['urllat','lon']] = df2['URL'].str.split(',', expand=True)
df2[['url1','url2','url3','url4','url5','lat']] = df2['urllat'].str.split('/', expand=True)
df2
cleaned_df = df2[['price_display','lat','lon','item1','item2','item3','item4','item5']]
cleaned_df = cleaned_df.drop(0)
cleaned_df

,price_display,lat,lon,item1,item2,item3,item4,item5
1,表示あり,40.7644,-73.9731185,コーヒー,ジュースなど,コールドブリューは$6,一部商品のみ表示,NaN
2,表示なし,40.7648035,-73.9733532,ジュース,アイス,NaN,NaN,NaN
3,表示あり,40.7667045,-73.9721405,ホットドッグ,アイス,ドリンク,NaN,NaN
4,表示あり,40.7649919,-73.9727591,チキンオーバーライス,ホットドッグなど,NaN,NaN,NaN
5,表示なし,40.7686219,-73.969988,ソフトクリーム,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
81,表示なし,40.7760205,-73.9759385,ハンバーガー,ホットドッグ,ドリンク,NaN,NaN
82,表示なし,40.776344,-73.9757893,ドリンク,スムージー,NaN,NaN,NaN
83,表示なし,40.7795244,-73.97344,チキンオーバーライス,ケバブ,ドリンクなど,NaN,NaN
84,表示なし,40.7807488,-73.9725459,ホットドッグ,ハンバーガーなど,NaN,NaN,NaN
85,表示なし,40.7808164,-73.9724657,チキンオーバーライス,ハンバーガー,ホットドッグなど,家族が購入,NaN

## Calculate the percentage of food trucks that display or do not display prices

In [71]:
cleaned_df['price_display'].value_counts()

price_display
表示なし    63
表示あり    22
Name: count, dtype: int64

In [88]:
cleaned_df['price_display'].value_counts(normalize=True)

price_display
表示なし    0.741176
表示あり    0.258824
Name: proportion, dtype: float64

cleaned_df.to_csv('cleaned_foodtruck_data.csv')